// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user.proto

package user

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	// 用户注册
	SignUp(ctx context.Context, in *UserSignUpReq, opts ...client.CallOption) (*UserSignUpResp, error)
	// 用户登录
	SignIn(ctx context.Context, in *UserSignInReq, opts ...client.CallOption) (*UserSignInResp, error)
	// 查询用户信息
	GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...client.CallOption) (*UserInfoResp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) SignUp(ctx context.Context, in *UserSignUpReq, opts ...client.CallOption) (*UserSignUpResp, error) {
	req := c.c.NewRequest(c.name, "User.SignUp", in)
	out := new(UserSignUpResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SignIn(ctx context.Context, in *UserSignInReq, opts ...client.CallOption) (*UserSignInResp, error) {
	req := c.c.NewRequest(c.name, "User.SignIn", in)
	out := new(UserSignInResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...client.CallOption) (*UserInfoResp, error) {
	req := c.c.NewRequest(c.name, "User.GetUserInfo", in)
	out := new(UserInfoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	// 用户注册
	SignUp(context.Context, *UserSignUpReq, *UserSignUpResp) error
	// 用户登录
	SignIn(context.Context, *UserSignInReq, *UserSignInResp) error
	// 查询用户信息
	GetUserInfo(context.Context, *UserInfoReq, *UserInfoResp) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		SignUp(ctx context.Context, in *UserSignUpReq, out *UserSignUpResp) error
		SignIn(ctx context.Context, in *UserSignInReq, out *UserSignInResp) error
		GetUserInfo(ctx context.Context, in *UserInfoReq, out *UserInfoResp) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) SignUp(ctx context.Context, in *UserSignUpReq, out *UserSignUpResp) error {
	return h.UserHandler.SignUp(ctx, in, out)
}

func (h *userHandler) SignIn(ctx context.Context, in *UserSignInReq, out *UserSignInResp) error {
	return h.UserHandler.SignIn(ctx, in, out)
}

func (h *userHandler) GetUserInfo(ctx context.Context, in *UserInfoReq, out *UserInfoResp) error {
	return h.UserHandler.GetUserInfo(ctx, in, out)
}
